-- ============================================================
-- MetroVerify – Supabase SQL Schema
-- Run this entire file in: Supabase Dashboard → SQL Editor → Run
-- ============================================================

-- Enable UUID generation
create extension if not exists "uuid-ossp";

-- ─────────────────────────────────────────────
-- 1. PROFILES  (extends Supabase auth.users)
-- ─────────────────────────────────────────────
create table public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  full_name     text not null,
  email         text not null,
  phone         text,
  role          text not null check (role in ('merchant','officer','gatc','admin')),
  organisation  text,
  state         text,
  district      text,
  is_active     boolean default true,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- Auto-insert profile row when a new user signs up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, full_name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    new.email,
    coalesce(new.raw_user_meta_data->>'role', 'merchant')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ─────────────────────────────────────────────
-- 2. INSTRUMENTS
-- ─────────────────────────────────────────────
create table public.instruments (
  id              uuid primary key default uuid_generate_v4(),
  owner_id        uuid not null references public.profiles(id) on delete cascade,
  name            text not null,
  instrument_type text not null,
  serial_number   text not null unique,
  seal_id         text unique,
  manufacturer    text,
  model           text,
  capacity        text,
  unit            text default 'kg',
  address         text,
  district        text,
  state           text,
  status          text default 'unverified'
                    check (status in ('unverified','valid','expiring','expired','under_review')),
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- ─────────────────────────────────────────────
-- 3. APPLICATIONS
-- ─────────────────────────────────────────────
create table public.applications (
  id              uuid primary key default uuid_generate_v4(),
  app_number      text unique,           -- e.g. APP-2026-0412 (generated by trigger)
  instrument_id   uuid not null references public.instruments(id) on delete cascade,
  applicant_id    uuid not null references public.profiles(id),
  assigned_to     uuid references public.profiles(id),  -- LMO / GATC officer
  pathway         text not null check (pathway in ('digital','physical')),
  status          text default 'submitted'
                    check (status in (
                      'submitted','under_review','evidence_requested',
                      'approved','escalated','rejected'
                    )),
  fee_amount      numeric(10,2),
  fee_paid        boolean default false,
  notes           text,
  remarks         text,                  -- officer remarks
  submitted_at    timestamptz default now(),
  reviewed_at     timestamptz,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- Auto-generate readable application number
create or replace function public.generate_app_number()
returns trigger language plpgsql as $$
begin
  new.app_number := 'APP-' || to_char(now(), 'YYYY') || '-' ||
                    lpad(nextval('app_number_seq')::text, 4, '0');
  return new;
end;
$$;

create sequence if not exists app_number_seq start 1000;

create trigger set_app_number
  before insert on public.applications
  for each row execute procedure public.generate_app_number();

-- ─────────────────────────────────────────────
-- 4. EVIDENCE  (photos / videos per application)
-- ─────────────────────────────────────────────
create table public.evidence (
  id              uuid primary key default uuid_generate_v4(),
  application_id  uuid not null references public.applications(id) on delete cascade,
  file_name       text not null,
  file_type       text not null check (file_type in ('photo','video','document')),
  storage_path    text not null,         -- Supabase Storage path
  public_url      text,
  uploaded_by     uuid references public.profiles(id),
  created_at      timestamptz default now()
);

-- ─────────────────────────────────────────────
-- 5. INSPECTION READINGS
-- ─────────────────────────────────────────────
create table public.inspection_readings (
  id              uuid primary key default uuid_generate_v4(),
  application_id  uuid not null references public.applications(id) on delete cascade,
  stage           text not null,         -- e.g. "Zero Load", "Test Load 1 (1kg)"
  reference_value text not null,
  observed_value  text,
  deviation       text,
  is_within_limit boolean,
  created_at      timestamptz default now()
);

-- ─────────────────────────────────────────────
-- 6. CERTIFICATES
-- ─────────────────────────────────────────────
create table public.certificates (
  id              uuid primary key default uuid_generate_v4(),
  cert_number     text unique,           -- e.g. MV-2026-TN-004521
  application_id  uuid not null references public.applications(id),
  instrument_id   uuid not null references public.instruments(id),
  issued_to       uuid not null references public.profiles(id),
  issued_by       uuid not null references public.profiles(id),
  verification_method text not null check (verification_method in ('digital','physical')),
  issued_at       timestamptz default now(),
  valid_from      date not null,
  valid_until     date not null,
  is_revoked      boolean default false,
  revoked_at      timestamptz,
  qr_payload      text,                  -- cryptographic payload for QR
  pdf_url         text,
  created_at      timestamptz default now()
);

-- Auto-generate readable certificate number
create or replace function public.generate_cert_number()
returns trigger language plpgsql as $$
declare
  state_code text;
begin
  select coalesce(substr(upper(i.state), 1, 2), 'IN')
    into state_code
    from public.instruments i
    where i.id = new.instrument_id;

  new.cert_number := 'MV-' || to_char(now(), 'YYYY') || '-' || state_code || '-' ||
                     lpad(nextval('cert_number_seq')::text, 6, '0');
  return new;
end;
$$;

create sequence if not exists cert_number_seq start 1000;

create trigger set_cert_number
  before insert on public.certificates
  for each row execute procedure public.generate_cert_number();

-- When a certificate is issued, update instrument status to 'valid'
create or replace function public.on_certificate_issued()
returns trigger language plpgsql as $$
begin
  update public.instruments
    set status = 'valid', updated_at = now()
    where id = new.instrument_id;

  update public.applications
    set status = 'approved', reviewed_at = now(), updated_at = now()
    where id = new.application_id;

  return new;
end;
$$;

create trigger after_certificate_issued
  after insert on public.certificates
  for each row execute procedure public.on_certificate_issued();

-- ─────────────────────────────────────────────
-- 7. NOTIFICATIONS
-- ─────────────────────────────────────────────
create table public.notifications (
  id              uuid primary key default uuid_generate_v4(),
  user_id         uuid not null references public.profiles(id) on delete cascade,
  type            text not null check (type in ('info','success','warning','danger')),
  title           text not null,
  body            text not null,
  action_label    text,
  action_url      text,
  is_read         boolean default false,
  created_at      timestamptz default now()
);

-- ─────────────────────────────────────────────
-- 8. ENFORCEMENT
-- ─────────────────────────────────────────────
create table public.enforcement_cases (
  id              uuid primary key default uuid_generate_v4(),
  case_number     text unique,
  instrument_id   uuid references public.instruments(id),
  reported_by     uuid references public.profiles(id),
  assigned_to     uuid references public.profiles(id),
  violation_type  text not null,
  severity        text not null check (severity in ('low','medium','high')),
  status          text default 'action_pending'
                    check (status in (
                      'action_pending','under_investigation',
                      'notice_issued','resolved'
                    )),
  description     text,
  district        text,
  detected_at     timestamptz default now(),
  resolved_at     timestamptz,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- ─────────────────────────────────────────────
-- 9. SCHEDULED INSPECTIONS
-- ─────────────────────────────────────────────
create table public.scheduled_inspections (
  id              uuid primary key default uuid_generate_v4(),
  application_id  uuid not null references public.applications(id),
  officer_id      uuid not null references public.profiles(id),
  scheduled_date  date not null,
  scheduled_time  time not null,
  location        text,
  district        text,
  status          text default 'upcoming'
                    check (status in ('upcoming','completed','cancelled','rescheduled')),
  notes           text,
  created_at      timestamptz default now()
);

-- ─────────────────────────────────────────────
-- 10. HELPER VIEWS
-- ─────────────────────────────────────────────

-- Applications with instrument + applicant joined
create or replace view public.applications_view as
select
  a.*,
  i.name            as instrument_name,
  i.instrument_type,
  i.serial_number,
  i.capacity,
  i.unit,
  i.district        as instrument_district,
  i.state           as instrument_state,
  p.full_name       as applicant_name,
  p.email           as applicant_email,
  p.phone           as applicant_phone,
  p.organisation    as applicant_org
from public.applications a
join public.instruments  i on i.id = a.instrument_id
join public.profiles     p on p.id = a.applicant_id;

-- Certificates with all related data joined
create or replace view public.certificates_view as
select
  c.*,
  i.name            as instrument_name,
  i.instrument_type,
  i.serial_number,
  i.seal_id,
  i.capacity,
  i.unit,
  i.manufacturer,
  i.model,
  i.address,
  i.district        as instrument_district,
  i.state           as instrument_state,
  p_owner.full_name  as owner_name,
  p_owner.organisation as owner_org,
  p_officer.full_name as officer_name
from public.certificates c
join public.instruments  i        on i.id = c.instrument_id
join public.profiles     p_owner  on p_owner.id = c.issued_to
join public.profiles     p_officer on p_officer.id = c.issued_by;

-- ─────────────────────────────────────────────
-- 11. ROW LEVEL SECURITY (RLS)
-- ─────────────────────────────────────────────

alter table public.profiles             enable row level security;
alter table public.instruments          enable row level security;
alter table public.applications         enable row level security;
alter table public.evidence             enable row level security;
alter table public.inspection_readings  enable row level security;
alter table public.certificates         enable row level security;
alter table public.notifications        enable row level security;
alter table public.enforcement_cases    enable row level security;
alter table public.scheduled_inspections enable row level security;

-- ── Profiles ──
create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

create policy "Admins can read all profiles"
  on public.profiles for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- ── Instruments ──
create policy "Merchants can manage own instruments"
  on public.instruments for all
  using (owner_id = auth.uid());

create policy "Officers can read all instruments"
  on public.instruments for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('officer','gatc','admin')
    )
  );

-- ── Applications ──
create policy "Merchants can manage own applications"
  on public.applications for all
  using (applicant_id = auth.uid());

create policy "Officers can read and update applications"
  on public.applications for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('officer','gatc','admin')
    )
  );

create policy "Officers can update assigned applications"
  on public.applications for update
  using (
    assigned_to = auth.uid()
    or exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('admin')
    )
  );

-- ── Evidence ──
create policy "Applicant can manage own evidence"
  on public.evidence for all
  using (uploaded_by = auth.uid());

create policy "Officers can view evidence"
  on public.evidence for select
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('officer','gatc','admin')
    )
  );

-- ── Certificates ──
create policy "Owners can view own certificates"
  on public.certificates for select
  using (issued_to = auth.uid());

create policy "Officers can manage certificates"
  on public.certificates for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('officer','gatc','admin')
    )
  );

-- Public certificate lookup (no auth needed) – for QR verify page
create policy "Public can read certificates by cert_number"
  on public.certificates for select
  using (true);

-- ── Notifications ──
create policy "Users can manage own notifications"
  on public.notifications for all
  using (user_id = auth.uid());

-- ── Enforcement ──
create policy "Admins and officers can manage enforcement"
  on public.enforcement_cases for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role in ('officer','admin')
    )
  );

-- ── Scheduled Inspections ──
create policy "Officers can manage their inspections"
  on public.scheduled_inspections for all
  using (
    officer_id = auth.uid()
    or exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'admin'
    )
  );

create policy "Merchants can view inspections for their applications"
  on public.scheduled_inspections for select
  using (
    exists (
      select 1 from public.applications a
      where a.id = application_id
        and a.applicant_id = auth.uid()
    )
  );

-- ─────────────────────────────────────────────
-- 12. UPDATED_AT AUTO-UPDATE TRIGGER
-- ─────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute procedure public.set_updated_at();

create trigger trg_instruments_updated_at
  before update on public.instruments
  for each row execute procedure public.set_updated_at();

create trigger trg_applications_updated_at
  before update on public.applications
  for each row execute procedure public.set_updated_at();

create trigger trg_enforcement_updated_at
  before update on public.enforcement_cases
  for each row execute procedure public.set_updated_at();

-- ─────────────────────────────────────────────
-- 13. STORAGE BUCKETS  (run manually or via Supabase Dashboard)
-- ─────────────────────────────────────────────
-- insert into storage.buckets (id, name, public)
--   values ('evidence', 'evidence', false);
-- insert into storage.buckets (id, name, public)
--   values ('certificates', 'certificates', true);

-- ============================================================
-- Schema complete. All tables, triggers, policies created.
-- ============================================================
